name = "github-token-broker"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "github-token-broker"

# KV Namespaces for rate limiting and device codes
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "YOUR_RATE_LIMIT_KV_ID"

[[kv_namespaces]]
binding = "DEVICE_CODES"
id = "YOUR_DEVICE_CODES_KV_ID"

# Environment variables (non-sensitive)
[vars]
GITHUB_API = "https://api.github.com"
ALLOWED_ORIGINS = ""

# Secrets (configure with wrangler secret put)
# GITHUB_APP_PRIVATE_KEY - PEM format private key
# GITHUB_APP_ID - Numeric App ID
# GITHUB_CLIENT_ID - App Client ID
# BROKER_CLIENT_SECRET - Shared HMAC secret
# CLOUDFLARE_TOKEN - For GitHub Actions deployment