name = "as-bot-worker"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "155ec15a52a18a14801e04b019da5e5a"

[env.production]
name = "as-bot-worker"

# KV Namespace for device codes
[[kv_namespaces]]
binding = "DEVICE_CODES"
id = "4d16c1ca5973424990ae00ab7f5c6bf7"

# KV Namespace for auth states (web flow)
# [[kv_namespaces]]
# binding = "AUTH_STATES"
# id = "NEEDS_TO_BE_CREATED"

# Environment variables (non-sensitive)
[vars]
GITHUB_API = "https://api.github.com"
ALLOWED_ORIGINS = ""

# Secrets (configure with wrangler secret put)
# GITHUB_APP_PRIVATE_KEY - PEM format private key
# GITHUB_APP_ID - Numeric App ID
# GITHUB_CLIENT_ID - App Client ID
# CLOUDFLARE_TOKEN - For GitHub Actions deployment